apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: "Sotatek-DatTruong/Training"
      labels:
        - "actions_runner_dev"
        - "pod-runner"